name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_APP: ${{ secrets.FLY_APP }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Fly client
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy using Remote Builder
        run: flyctl deploy --app="$FLY_APP" --remote-only --no-cache
