app = "redis"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data"
  source = "redis_server"

[[services]]
  internal_port = 6379
  protocol = "tcp"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
